# Generated by Django 5.2.7 on 2025-10-30 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_exercise_options_exercise_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(through='workout.WorkoutExercise', to='workout.exercise'),
        ),
    ]
